# Generated by Django 4.0.4 on 2022-05-17 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256, null=True)),
                ('average_rating', models.DecimalField(decimal_places=1, max_digits=10, null=True)),
                ('guests', models.CharField(max_length=256, null=True)),
                ('room_type', models.CharField(max_length=256, null=True)),
                ('house_type', models.CharField(max_length=256, null=True)),
                ('beds', models.CharField(max_length=256, null=True)),
                ('baths', models.CharField(max_length=256, null=True)),
                ('is_new_listing', models.BooleanField()),
                ('title', models.CharField(max_length=256, null=True)),
                ('lat', models.DecimalField(decimal_places=7, max_digits=10, null=True)),
                ('lng', models.DecimalField(decimal_places=7, max_digits=10, null=True)),
                ('rate', models.CharField(max_length=256, null=True)),
                ('amount', models.IntegerField(null=True)),
                ('city', models.CharField(max_length=256, null=True)),
                ('picture', models.CharField(max_length=256, null=True)),
                ('rating_count', models.IntegerField(null=True)),
            ],
        ),
    ]
