# Generated by Django 4.0.4 on 2022-05-17 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('overview', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='rating_count',
            new_name='reviews_count',
        ),
    ]
