# Generated by Django 4.0.4 on 2022-05-22 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('overview', '0003_listing_country_alter_listing_city'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listing',
            options={'ordering': ['id', 'country', 'city', 'name', 'title', 'average_rating', 'room_type', 'house_type', 'beds', 'lat', 'lng', 'rate', 'amount', 'picture', 'reviews_count']},
        ),
    ]
